### PR TITLE
Attempting to modify _meta schema for pmd data theme

### PR DESCRIPTION
**Pull request by pulsifer**
Based on e-mail thread with Spencer Cox, Peter Pulsifer has attempted to add a number of metadata elements based on the Polar Data Catalogue (PDC) implementation of the ISO 19115 metadata standard.  See commit comments for more details.  Note that if accepted, these changes will not make the system ISO 19115 or PDC compliant, however it will move the system in that direction.  This work was based on a document provided by a project partner.  It is clear that that in that document there is a mix of data theme metadata (i.e. would apply to all samples), data sample metadata (i.e. different for each sample) and items that might be considered as part of the data rather than metadata (e.g. depth of sample).

### CODE REVIEW

**Comment by MishtuBanerjee** [comment]
Sample = Dataset?

**Comment by pulsifer** [comment]
My interpretation is that an individual sample is = record or observation.  A collection of samples would be a data set.  I am not the authority on this, though.  Should refer to Gordon or GNWT.

**Comment by MishtuBanerjee** [comment]
Ahh ... thanks ... that makes things clearer. 

Sample ~ Record. 

Data Set: A collection of records. 

Theme: A collection of data sets. 

Is this correct from your perspective?

And metadata exists at level of Record, Dataset, Theme ?

**Comment by pulsifer** [comment]
This is my understanding.

If we think about a use case, field personnel would return from collecting data from a sensor.  A particular sensor might take one sample per day and be collected monthly.  So, this person would return from the field with a "Data Set" (collection of record)  of 30 samples  (records).  This data set would then be added to the the data theme which would be a set for that type of sensor over a longer period of time (e.g. a two year monitoring program).  

There could be metadata at all levels.  Theme level metadata (what I have included in my pull request) would be constant for a theme.  However, GNWT has also identified metadata that would be appropriate for each sample.   See the attached PDF file.  This needs further investigation with GNWT as it appears to me that some of what they might call metadata (e.g. depth of sample) might be more appropriately considered data (it could change from sample to sample?).  I do not see much in the way of metadata that would be specific to a data set (individual file), however I may be misinterpreting as I am not an expert in this type of data.

My expertise is not in the area of water quality data, so as I indicated my word is not authoritative.  My advice is in relation to the Theme level metadata and linking to broader metadata standards.

Best,

Peter

**Comment by MishtuBanerjee** [comment]
Thanks Peter.

That is a really clear use case and indeed as you say: "There could be metadata at all levels".

Depth of Sample, does look like something that could be more appropriately considered data. It might be, that it's invariant for a "Data Set", and that's why it is being treated as meta-data; rather than entered as another field with each record. 

So -- with respect to your mention of meta-data tied to the sample level; whether it be treated as meta-data or data might depend on whether it's value is uniform across all samples (treat as metadata) or can vary from sample (observation/record) to sample (potentially treat as data).

**Comment by pulsifer** [comment]
Hi Mishtu,

Completely agree.  This is why some more input from GNWT would be good.  I suspect that this is a situation where the intention may be to keep a value constant.  So, the depth of the sensor should always be 2.00 meters.  However, in my past life life as a field scientist, best laid plans do not always working out which can mean the depth on a given day may be 2.47 meters (for example).  In their current workflow, which seems to be based on forms and spreadsheets, it would be very easy to accommodate this variation.  However, if we design a system where metadata is constant, they may find themselves experiencing difficulty.  

As you point out, a simple rule to establish data vs. metadata is the whether a value remains constant.  Gila or others at GNWT should be able to advise here.

**Comment by MishtuBanerjee** [comment]
Agree -- have to look at effect of more constant (standardized) meta data -- on their current spreadsheet rather than database oriented workflows. 

My past life was as a field scientist too (botanist and forester). So I empathize when reality hijacks best laid plans.

**Pull request closed without merging**
